# Generated by Django 3.2.9 on 2022-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_from_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_system_from_client',
            field=models.BooleanField(default=True),
        ),
    ]
