# Generated by Django 3.2.9 on 2022-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220121_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_status',
            field=models.IntegerField(choices=[(0, 'Клиент'), (1, 'Партнёр'), (2, 'Дилер')], default=0),
        ),
    ]
