# Generated by Django 3.2.9 on 2022-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='contacts',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
