# Generated by Django 3.2.9 on 2022-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerprofile_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='post_adress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
