# Generated by Django 3.2.9 on 2022-01-28 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0027_alter_kkt_data_end_of_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0003_alter_partnerprofile_post_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 1, 28, 19, 56, 48, 439049, tzinfo=utc))),
                ('payment_status', models.CharField(default='Не оплачен', max_length=30)),
                ('kkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkt_check.kkt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
