# Generated by Django 3.2.9 on 2022-01-29 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 14, 9, 38, 446077, tzinfo=utc)),
        ),
    ]
