# Generated by Django 3.2.9 on 2022-01-30 17:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0005_alter_contract_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 3, 16, 331184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 3, 16, 331184, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 3, 16, 332180, tzinfo=utc))),
                ('payment_status', models.CharField(default='Не активирован', max_length=30)),
                ('mounth_payment_count', models.IntegerField(default=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
