# Generated by Django 3.2.9 on 2022-01-30 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20220130_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 19, 40, 3, 652827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 19, 40, 3, 652827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 19, 40, 3, 653830, tzinfo=utc)),
        ),
    ]
