# Generated by Django 3.2.9 on 2022-01-31 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20220131_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeorder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 47, 3, 812747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codeorder',
            name='mounth_payment_count',
            field=models.IntegerField(choices=[(12, 'Тариф 12 Месяцев'), (1, 'Тариф 1 Месяц'), (3, 'Тариф Квартал')], default=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 47, 3, 811673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 47, 3, 811673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 47, 3, 812747, tzinfo=utc)),
        ),
    ]
