# Generated by Django 3.2.9 on 2022-01-31 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20220131_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeorder',
            name='code_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='codeorder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 57, 21, 112782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 57, 21, 111756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 57, 21, 111756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 17, 57, 21, 112782, tzinfo=utc)),
        ),
    ]
