# Generated by Django 3.2.9 on 2022-02-23 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20220131_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeorder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 13, 10, 29, 645509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 13, 10, 29, 645509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 13, 10, 29, 645509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 13, 10, 29, 645509, tzinfo=utc)),
        ),
    ]
