# Generated by Django 3.2.9 on 2022-11-23 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20221123_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeorder',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 17, 41, 39, 954703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 17, 41, 39, 953613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 17, 41, 39, 953613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 17, 41, 39, 954703, tzinfo=utc)),
        ),
    ]
