# Generated by Django 3.2.9 on 2021-11-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('inn_kkt', models.CharField(max_length=12)),
                ('fn_number', models.CharField(max_length=16)),
                ('cashier_name', models.CharField(max_length=50)),
                ('cashier_inn', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Check_kkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shft_num', models.IntegerField()),
                ('check_num', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_inn', models.CharField(max_length=12)),
                ('tax_system', models.CharField(max_length=1)),
                ('send_check_to', models.CharField(max_length=50)),
                ('cash', models.IntegerField()),
                ('ecash', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('kkt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkt_check.kkt')),
            ],
        ),
        migrations.CreateModel(
            name='Check_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('tax_code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_type_code', models.IntegerField()),
                ('check_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkt_check.check_kkt')),
            ],
        ),
    ]
