# Generated by Django 3.2.9 on 2021-11-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check_kkt',
            options={'verbose_name_plural': 'kkt_names'},
        ),
    ]
