# Generated by Django 3.2.9 on 2021-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0002_alter_check_kkt_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_kkt',
            old_name='kkt_name',
            new_name='kkt',
        ),
        migrations.AlterField(
            model_name='check_good',
            name='product_type_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='check_good',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='check_good',
            name='tax_code',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='buyer_inn',
            field=models.CharField(default='0000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='check_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='shft_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='status',
            field=models.CharField(default='Добавлен', max_length=10),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='tax_system',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
