# Generated by Django 3.2.9 on 2021-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0004_kkt_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check_kkt',
            options={'verbose_name_plural': 'kkts'},
        ),
        migrations.RenameField(
            model_name='check_good',
            old_name='check_name',
            new_name='check_kkt',
        ),
        migrations.AlterField(
            model_name='kkt',
            name='cashier_inn',
            field=models.CharField(default='0000000000', max_length=12),
        ),
    ]
