# Generated by Django 3.2.9 on 2021-11-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0007_rename_checkkkt_check_good_check_kkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_good',
            name='check_kkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkkktset', to='kkt_check.check_kkt'),
        ),
    ]
