# Generated by Django 3.2.9 on 2022-01-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0009_alter_check_good_product_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_good',
            name='tax_code',
            field=models.IntegerField(choices=[(6, 'Ндснеоблагается'), (1, 'Ставкандс 20'), (2, 'Ставкандс 10'), (5, 'Ставкандс 0')], default=6),
        ),
    ]
