# Generated by Django 3.2.9 on 2022-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0010_alter_check_good_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_good',
            name='qty',
            field=models.IntegerField(default=10000),
        ),
    ]
