# Generated by Django 3.2.9 on 2022-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0012_alter_check_good_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_kkt',
            name='tax_system',
            field=models.CharField(choices=[('0', 'Общая'), ('1', 'Упрощенная Доходы'), ('2', 'Упрощенная Доходы Минус Расходы'), ('5', 'Патент')], default='0', max_length=1),
        ),
    ]
