# Generated by Django 3.2.9 on 2022-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0013_alter_check_kkt_tax_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_kkt',
            name='bot_message_id',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
