# Generated by Django 3.2.9 on 2022-01-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0014_check_kkt_bot_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_kkt',
            name='status',
            field=models.CharField(default='Добавлен', max_length=60),
        ),
    ]
