# Generated by Django 3.2.9 on 2022-01-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0016_alter_check_kkt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_kkt',
            name='buyer_inn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check_kkt',
            name='ecash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='cashier_inn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='cashier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
