# Generated by Django 3.2.9 on 2022-01-09 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0017_auto_20220105_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
