# Generated by Django 3.2.9 on 2022-01-20 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0021_alter_kkt_data_end_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_kkt',
            name='send_check_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 19, 1, 20, 56602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='fn_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
