# Generated by Django 3.2.9 on 2022-01-21 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0022_auto_20220120_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='kkt',
            name='tax_code',
            field=models.IntegerField(choices=[(6, 'Ндс Не Облагается'), (1, 'Ставка Ндс 20'), (2, 'Ставка Ндс 10'), (5, 'Ставка Ндс 0')], default=6),
        ),
        migrations.AddField(
            model_name='kkt',
            name='tax_system',
            field=models.CharField(choices=[('0', 'Общая'), ('1', 'Упрощенная Доходы'), ('2', 'Упрощенная Доходы Минус Расходы'), ('5', 'Патент')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 20, 1, 37, 671410, tzinfo=utc)),
        ),
    ]
