# Generated by Django 3.2.9 on 2022-01-23 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0023_auto_20220121_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 17, 43, 58, 596815, tzinfo=utc)),
        ),
    ]
