# Generated by Django 3.2.9 on 2022-01-28 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0026_alter_kkt_data_end_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 19, 56, 48, 436013, tzinfo=utc)),
        ),
    ]
