# Generated by Django 3.2.9 on 2022-01-30 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0031_alter_kkt_data_end_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 21, 13, 14, 985863, tzinfo=utc)),
        ),
    ]
