# Generated by Django 3.2.9 on 2022-02-23 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0035_alter_kkt_data_end_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkt',
            name='data_end_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 13, 10, 29, 642519, tzinfo=utc)),
        ),
    ]
