# Generated by Django 3.2.9 on 2022-01-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0009_alter_check_good_product_type_code'),
        ('bot', '0003_alter_botuser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_сheck_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_check.check_kkt'),
        ),
    ]
