# Generated by Django 3.2.9 on 2022-01-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_check', '0010_alter_check_good_tax_code'),
        ('bot', '0005_rename_current_сheck_id_botuser_current_сheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_check.check_good'),
        ),
    ]
